// Exports the types generated by Prisma (models, enums)
export * from '@prisma/client';

// Exports the injectable Prisma service for NestJS applications
export { PrismaService } from './PrismaService.js';
